const bcrypt = require('bcryptjs');

module.exports = {
  /**
   * Seed 5 danh mục sản phẩm chính (từ file Excel)
   */
  categories: [
    {
      name_en: 'Premium Shrimp',
      name_vi: 'Tôm Cao Cấp',
      slug: 'shrimp',
      sort_order: 1,
      is_active: true,
    },
    {
      name_en: 'Squid, Octopus & Cuttlefish',
      name_vi: 'Mực & Bạch Tuộc',
      slug: 'cephalopods',
      sort_order: 2,
      is_active: true,
    },
    {
      name_en: 'Marine Fish',
      name_vi: 'Cá Biển',
      slug: 'marine-fish',
      sort_order: 3,
      is_active: true,
    },
    {
      name_en: 'Freshwater Fish',
      name_vi: 'Cá Nước Ngọt',
      slug: 'freshwater-fish',
      sort_order: 4,
      is_active: true,
    },
    {
      name_en: 'Amphibians & Shellfish',
      name_vi: 'Ếch & Loài Có Vỏ',
      slug: 'shellfish',
      sort_order: 5,
      is_active: true,
    },
  ],

  /**
   * Sản phẩm mẫu (từ nội dung file Excel)
   */
  products: [
    // === SHRIMP ===
    {
      categorySlug: 'shrimp',
      name_en: 'Frozen Vannamei Shrimp - Breaded',
      name_vi: 'Tôm thẻ chân trắng tẩm bột đông lạnh',
      slug: 'frozen-vannamei-shrimp-breaded',
      short_desc_en: 'Vannamei Breaded shrimp, premium quality from certified Vietnamese processing plants.',
      short_desc_vi: 'Tôm thẻ chân trắng tẩm bột, chất lượng cao cấp từ nhà máy chế biến đạt chuẩn Việt Nam.',
      product_type: 'value_added',
      is_featured: true,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Litopenaeus vannamei', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '16/20, 21/25, 26/30, 31/40', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF', sort_order: 4 },
        { spec_key_en: 'Glazing', spec_key_vi: 'Tỷ lệ mạ băng', spec_value: '0%, 5%, 10%, 15%, 20%', sort_order: 5 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Bulk carton 10kg, Retail bag', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS, ASC, BAP', sort_order: 7 },
      ],
    },
    {
      categorySlug: 'shrimp',
      name_en: 'Frozen Vannamei Shrimp - Lychee Style',
      name_vi: 'Tôm thẻ chân trắng kiểu Trái Vải',
      slug: 'frozen-vannamei-shrimp-lychee',
      short_desc_en: 'Unique lychee-shaped Vannamei shrimp, ready for premium food service.',
      short_desc_vi: 'Tôm thẻ tạo hình trái vải độc đáo, sẵn sàng phục vụ ẩm thực cao cấp.',
      product_type: 'value_added',
      is_featured: false,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Litopenaeus vannamei', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '26/30, 31/40', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF', sort_order: 4 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Retail box 500g, Bulk carton 10kg', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS', sort_order: 7 },
      ],
    },
    {
      categorySlug: 'shrimp',
      name_en: 'Crispy Shrimp Popcorn',
      name_vi: 'Tôm Popcorn giòn',
      slug: 'crispy-shrimp-popcorn',
      short_desc_en: 'Crispy bite-sized breaded shrimp popcorn, perfect for retail and food service.',
      short_desc_vi: 'Tôm viên tẩm bột giòn vừa ăn, phù hợp bán lẻ và dịch vụ ẩm thực.',
      product_type: 'value_added',
      is_featured: false,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Litopenaeus vannamei', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF', sort_order: 4 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Retail bag 300g, Bulk carton 5kg', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC', sort_order: 7 },
      ],
    },

    // === CEPHALOPODS ===
    {
      categorySlug: 'cephalopods',
      name_en: 'Whole Cleaned Squid',
      name_vi: 'Mực ống nguyên con làm sạch',
      slug: 'whole-cleaned-squid',
      short_desc_en: 'Whole cleaned squid, fully gutted and skinned, ideal for grilling and frying.',
      short_desc_vi: 'Mực ống nguyên con làm sạch hoàn toàn, lý tưởng cho nướng và chiên.',
      product_type: 'raw',
      is_featured: true,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Loligo spp.', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '8/12, 12/16, 16/20 cm', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF / Block Frozen', sort_order: 4 },
        { spec_key_en: 'Glazing', spec_key_vi: 'Tỷ lệ mạ băng', spec_value: '5%, 10%', sort_order: 5 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Bulk carton 10kg', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS', sort_order: 7 },
      ],
    },
    {
      categorySlug: 'cephalopods',
      name_en: 'Squid Rings - Pineapple Cut',
      name_vi: 'Mực cắt khoanh kiểu hoa',
      slug: 'squid-rings-pineapple-cut',
      short_desc_en: 'Premium squid rings with decorative pineapple cut, ready for tempura or stir-fry.',
      short_desc_vi: 'Mực cắt khoanh hoa cao cấp, sẵn sàng cho tempura hoặc xào.',
      product_type: 'raw',
      is_featured: false,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Loligo spp.', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'Block Frozen 7.5kg', sort_order: 4 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Block 7.5kg / 16.5 lb', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS', sort_order: 7 },
      ],
    },
    {
      categorySlug: 'cephalopods',
      name_en: 'Baby Octopus - Whole Cleaned',
      name_vi: 'Bạch tuộc baby nguyên con làm sạch',
      slug: 'baby-octopus-whole-cleaned',
      short_desc_en: 'Tender baby octopus, fully cleaned, perfect for grilling or salads.',
      short_desc_vi: 'Bạch tuộc baby mềm, làm sạch hoàn toàn, hoàn hảo cho nướng hoặc salad.',
      product_type: 'raw',
      is_featured: false,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Octopus spp.', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '20/40, 40/60 pcs/kg', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF', sort_order: 4 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'IQF Bulk carton 10kg', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC', sort_order: 7 },
      ],
    },

    // === MARINE FISH ===
    {
      categorySlug: 'marine-fish',
      name_en: 'Tuna Loin - Sashimi Grade',
      name_vi: 'Thịt thăn cá ngừ - Chuẩn Sashimi',
      slug: 'tuna-loin-sashimi-grade',
      short_desc_en: 'Premium sashimi-grade Tuna loins, CO treated for vibrant color retention.',
      short_desc_vi: 'Thịt thăn cá ngừ chuẩn Sashimi cao cấp, xử lý CO giữ màu tươi sáng.',
      product_type: 'raw',
      is_featured: true,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Thunnus albacares (Yellowfin)', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '2-4 kg/pc', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'Super frozen -60°C / Vacuum packed', sort_order: 4 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Vacuum pack, Carton 10-20kg', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS, ISO', sort_order: 7 },
      ],
    },
    {
      categorySlug: 'marine-fish',
      name_en: 'Mahi Mahi Fillet',
      name_vi: 'Phi lê cá Dũa (Mahi Mahi)',
      slug: 'mahi-mahi-fillet',
      short_desc_en: 'Skinless, boneless Mahi Mahi fillets, ideal for grilling and baking.',
      short_desc_vi: 'Phi lê cá Dũa không da không xương, lý tưởng cho nướng và nấu.',
      product_type: 'raw',
      is_featured: false,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Coryphaena hippurus', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '200-400g, 400-600g/pc', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF / IVP', sort_order: 4 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'IVP Vacuum pack, Carton 10kg', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS', sort_order: 7 },
      ],
    },

    // === FRESHWATER FISH ===
    {
      categorySlug: 'freshwater-fish',
      name_en: 'Pangasius (Basa) Fillet - Well Trimmed',
      name_vi: 'Phi lê cá Tra (Basa) - Cắt tỉa sạch',
      slug: 'pangasius-basa-fillet-well-trimmed',
      short_desc_en: 'Well-trimmed Pangasius fillet, white meat, no fat, no bone, export standard.',
      short_desc_vi: 'Phi lê cá Tra cắt tỉa sạch, thịt trắng, không mỡ, không xương, chuẩn xuất khẩu.',
      product_type: 'raw',
      is_featured: true,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Pangasius hypophthalmus', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam (Mekong Delta)', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '120-170g, 170-220g, 220-up', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF / Semi-block', sort_order: 4 },
        { spec_key_en: 'Glazing', spec_key_vi: 'Tỷ lệ mạ băng', spec_value: '10%, 15%, 20%', sort_order: 5 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Bulk poly bag 1kg x 10, IVP', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS, ASC, BAP, ISO', sort_order: 7 },
      ],
    },
    {
      categorySlug: 'freshwater-fish',
      name_en: 'Tilapia Fillet',
      name_vi: 'Phi lê cá Điêu hồng (Rô phi)',
      slug: 'tilapia-fillet',
      short_desc_en: 'Deep-skinned Tilapia fillet, consistent size, ideal for fish & chips and industrial use.',
      short_desc_vi: 'Phi lê cá Điêu hồng lột da sạch, kích cỡ đồng đều, phù hợp chế biến công nghiệp.',
      product_type: 'raw',
      is_featured: false,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Oreochromis niloticus', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '80-120g, 120-170g, 170-230g', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF / Block Frozen', sort_order: 4 },
        { spec_key_en: 'Glazing', spec_key_vi: 'Tỷ lệ mạ băng', spec_value: '10%, 20%', sort_order: 5 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Bulk carton 10kg, IVP', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, ASC', sort_order: 7 },
      ],
    },

    // === SHELLFISH & AMPHIBIANS ===
    {
      categorySlug: 'shellfish',
      name_en: 'Premium Frog Legs',
      name_vi: 'Đùi ếch cao cấp',
      slug: 'premium-frog-legs',
      short_desc_en: 'Premium frog legs, cleaned, trimmed and individually quick frozen for export.',
      short_desc_vi: 'Đùi ếch cao cấp, làm sạch, cắt tỉa và cấp đông nhanh IQF cho xuất khẩu.',
      product_type: 'raw',
      is_featured: true,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Rana spp.', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '2/4, 4/6, 6/8, 8/12 pairs/lb', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF', sort_order: 4 },
        { spec_key_en: 'Glazing', spec_key_vi: 'Tỷ lệ mạ băng', spec_value: '0%, 10%', sort_order: 5 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Bulk carton 10kg', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS', sort_order: 7 },
      ],
    },
    {
      categorySlug: 'shellfish',
      name_en: 'Frozen Scallop Meat - IQF',
      name_vi: 'Cồi sò điệp đông lạnh - IQF',
      slug: 'frozen-scallop-meat-iqf',
      short_desc_en: 'Pure scallop meat, shucked and cleaned, individually quick frozen for premium quality.',
      short_desc_vi: 'Cồi sò điệp nguyên chất, tách vỏ làm sạch, cấp đông nhanh IQF chất lượng cao.',
      product_type: 'raw',
      is_featured: false,
      specifications: [
        { spec_key_en: 'Scientific Name', spec_key_vi: 'Tên khoa học', spec_value: 'Placopecten magellanicus', sort_order: 1 },
        { spec_key_en: 'Origin', spec_key_vi: 'Xuất xứ', spec_value: 'Vietnam', sort_order: 2 },
        { spec_key_en: 'Size / Counting', spec_key_vi: 'Kích cỡ', spec_value: '10/20, 20/30, 30/40 pcs/lb', sort_order: 3 },
        { spec_key_en: 'Freezing Method', spec_key_vi: 'Quy cách cấp đông', spec_value: 'IQF', sort_order: 4 },
        { spec_key_en: 'Glazing', spec_key_vi: 'Tỷ lệ mạ băng', spec_value: '5%, 10%', sort_order: 5 },
        { spec_key_en: 'Packaging', spec_key_vi: 'Quy cách đóng gói', spec_value: 'Individual bags 1lb, Bulk carton 10kg', sort_order: 6 },
        { spec_key_en: 'Certificates', spec_key_vi: 'Chứng chỉ', spec_value: 'HACCP, BRC, IFS', sort_order: 7 },
      ],
    },
  ],

  /**
   * Admin user mặc định
   */
  adminUser: {
    username: 'admin',
    password_hash: bcrypt.hashSync('Admin@2026', 10),
    email: 'admin@goldenseafood.com.vn',
    full_name: 'Administrator',
    role: 'admin',
    is_active: true,
  },
};
